# Generated by Django 5.2.1 on 2025-05-28 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol, must be unique per user', max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('shares', models.PositiveIntegerField(help_text='Current number of shares owned', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_price', models.FloatField(help_text='Average price per share (USD)', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol, e.g., AAPL', max_length=10, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='Type of trade: BUY or SELL', max_length=4)),
                ('shares', models.PositiveIntegerField(help_text='Number of shares (must be >= 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(help_text='Price per share in USD', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the trade was executed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
